### ISSUE TITLE
output of detect_failed_subjects.py

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_preprocess2#10]
I just ran this on a directory and there are potentially two issues. Here is the relevant output:

```
26 subjects faced some error during preprocessing: {'sub-70035', 'sub-11090', 'sub-70036', 'sub-10704', 'sub-10517', 'sub-10388', 'sub-10377', 'sub-10678', 'sub-10428', 'sub-10492', 'sub-10971', 'sub-10912', 'sub-11121', 'sub-50083', 'sub-70081', 'sub-70061', 'sub-50075', 'sub-60089', 'sub-70077', 'sub-10280', 'sub-10501', 'sub-10440', 'sub-70029', 'sub-10299', 'sub-10448', 'sub-70065'}
5 subjects were timed out and error did not get propagated: {'sub-60057', 'sub-70051', 'sub-60060', 'sub-50035', 'sub-60036'}
1 subjects were timed out: {'sub-10998'}
Increased wall time and try to resubmit again.
8 subjects ran out of space in `localscratch`: {'sub-10280', 'sub-10998', 'sub-70029', 'sub-10704', 'sub-10517', 'sub-10678', 'sub-70065', 'sub-60089'}
Added request for 10 GB of space and try to resubmit again.
5 subjects were timed out and error did not get propagated: {'sub-60057', 'sub-70051', 'sub-60060', 'sub-50035', 'sub-60036'}
```

and the contents of `.slurm_modified`:
```
modified_smriprep_sub-10280.sh  modified_smriprep_sub-60057.sh
modified_smriprep_sub-10517.sh  modified_smriprep_sub-60060.sh
modified_smriprep_sub-10678.sh  modified_smriprep_sub-60089.sh
modified_smriprep_sub-10704.sh  modified_smriprep_sub-70029.sh
modified_smriprep_sub-10998.sh  modified_smriprep_sub-70051.sh
modified_smriprep_sub-50035.sh  modified_smriprep_sub-70065.sh
modified_smriprep_sub-60036.sh
```

1)  26 subjects failed, but 14 are mentioned below. I assume this means we are missing some error messages.
2) the message `5 subjects were timed out and error did not get propagated: {'sub-60057', 'sub-70051', 'sub-60060', 'sub-50035', 'sub-60036'}` is repeated. It also generates modified slurm files for these subjects (without any changes), which it doesn't need to. 

I can look into both of these!

**Comment by clarkenj** [comment]
New error messages found:

1.  `No T1w images found` (70035, 70036, 10428, 10971, 11121, 10501, 10299)
2. `rsync error: some files/attrs were not transferred (see previous errors)` (11090, 10492, 10912, 50083, 70081, 70061, 50075, 70077)
3. `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error. Background on this error at: http://sqlalche.me/e/13/e3q8` (10388, 10377, 10440, 10448)
4. 10280 does not seem to have any errors, just a FutureWarning

1 and 4 are lost causes. 2 (there are no 'previous errors' listed) and 3, I am tempted to just move on to the next dataset given time constraints.

**Comment by htwangtw** [comment]
If you can copy the logs, I can use it as test data to further resolve the issue and perhaps improve the documentations:
```
mkdir test_data
cd test_data
rsync -chavzPR --stats $CC_USERNAME@beluga.computecanada.ca:scratch/path_to/./dataset_name/fmriprep*/sub-*/log/* .
rsync -chavzPR --stats $CC_USERNAME@beluga.computecanada.ca:scratch/path_to/./dataset_name/.slurm/* .
rsync -chavzPR --stats $CC_USERNAME@beluga.computecanada.ca:scratch/path_to/./dataset_name/smriprep_* .
cd ..
tar -czvf test_data.tar.gz test_data
```
The `/./` tells `rsync` to keep the directory structure from that point on. 
Remember to make sure the user name and path are correct.

**Comment by clarkenj** [comment]
I think we can close this issue. I have updated detect_failed_subjects.py since, and I stupidly didn't actually write which dataset this was referring to for copying the logs.
